### ISSUE TITLE
Move cl-urdf into roslisp_common

### ISSUE THREAD

**Issue by airballking** [cram-code/cram_physics#20]
Moving ```cl-urdf``` into ```roslisp-common``` seems like a good idea because users outside of cram could be interested in using urdfs from common lisp.

The only problem that we have is that ```cl-urdf``` depends on ```physics-utils``` to automatically load meshes. This needs to be refactored before moving this out.

@jannikb Could you please look at this?

I'll invite @gaya- and @bbrieber to help reviewing your pull requests, once you're done with this.

**Comment by gaya-** [comment]
Great idea, I'll help testing. I could also provide a small code snippet with a working example of ```cl-urdf usage``` if needed.

**Comment by gaya-** [comment]
Solved in https://github.com/cram-code/cram_physics/pull/22 and https://github.com/cram-code/cram_physics/pull/24
